server:
  port: 8888
 
spring:
  cloud:
    gateway:
      routes:
      - id: microservicio1
        uri: http://localhost:8081/
        predicates:
        - Path=/microservicio1/**
      - id: microservicio2
        uri: http://localhost:8082/
        predicates:
        - Path=/microservicio2/**

